### PR TITLE
no longer press enter to leave Game Over screen

### PR DESCRIPTION
**Pull request by PyDario**
You can no longer leave the Game Over screen by pressing Enter.

### CODE REVIEW

**Comment by ChLah** [comment]
Should solve issue #27

**Review by ChLah — CHANGES_REQUESTED** [review]
See issue #21 :

> So if the focus is in the input text, we should submit the highscore and not leave (at least when there is something typed in)

**Comment by ChLah** [comment]
You should wait for the request to complete, as if we'd be redirecting to main. Also, you should possibly remove your debug messages

**Comment by PyDario** [comment]
You can now submit your score by pressing Enter and be redirected to the Highscore screen
Closes #22 and #21

**Pull request merged**
